### ISSUE TITLE
update for coredns master

### ISSUE THREAD

**Issue by miekg** [serverwentdown/alias#1]
We've renamed middleware to plugin to have more consitant naming and keep in sync with caddy.

For the example plugin, this diff we needed; it is just renaming middleware to plugin:
see https://github.com/coredns/example/commit/fe5e8f02ad4b76d7b8701303414fe28e75c0825b

**Comment by serverwentdown** [comment]
okay, will make change soon.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [serverwentdown/alias] update f..." ]
>okay, will make change soon.

Thanks. I think you just need to do:

~~~
sed 's/middleware/plugin/'g -i *.go
sed 's/Middleware/Plugin/'g -i *.go
~~~
