### ISSUE TITLE
Compiling 1.8.0 breaks building when using this plugin

### ISSUE THREAD

**Issue by xunholy** [serverwentdown/alias#6]
When I add this plugin and try to compile coredns I get the following error:

```
#8 92.73 go: github.com/coredns/coredns imports
#8 92.73 	github.com/coredns/coredns/core/plugin imports
#8 92.73 	github.com/jiachengxu/idetcd imports
#8 92.73 	github.com/mholt/caddy/onevent: github.com/mholt/caddy@v1.0.5: parsing go.mod:
#8 92.73 	module declares its path as: github.com/caddyserver/caddy
#8 92.73 	        but was required as: github.com/mholt/caddy
```

The 1.8.0 coredns logs mention this in their release notes:
```
Caddy is now developing a version 2 and we are using version 1, we've internalized
Caddy into <https://github.com/coredns/caddy>. This means the `caddy` types change and *all* plugins
need to fix the import path from: `github.com/caddyserver/caddy` to `github.com/coredns/caddy` (this
can thankfully be automated).
```

**Comment by serverwentdown** [comment]
Ah yes, I forgot about keeping this up to date. I'd probably fix this over the weekend, but feel free to make a PR.

**Comment by xunholy** [comment]
I believe there is already a forked fix that shoud be merged upstream https://github.com/hennemon/coredns-alias/commit/815bec6ca60f52cc1f104f440db91a2c9c971e53

@hennemon

**Comment by xunholy** [comment]
@serverwentdown is this plugin going to likely work with the etcd plugin?

**Comment by serverwentdown** [comment]
Oh sweet I'll merge that in. I haven't tested it in conjunction, you could try.

**Comment by serverwentdown** [comment]
A little busy this weekend, so I did not manage to get it done. Feel free to file a PR
